services:
  - type: web
    name: vhom-ai
    runtime: python
    repo: https://github.com/SHADOW-VRX/VHOM-AI
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://vhom-ai.onrender.com
